version: '3.6'

x-uffizzi:
  ingress:
    service: traefik
    port: 1337

services:
  traefik:
    image: "traefik:v2.5"
    command:
      - "--api.insecure=true"
      - "--entrypoints.web.address=:1337"
      - "--providers.file.directory=/traefik"
    volumes: 
      - ./examples/docker-compose/traefik.yaml:/traefik/traefik.yaml

  postgres:
    image: postgres:14.6
#    volumes:
#      - ./data/db:/var/lib/postgresql/data
#      - ./initdb.d:/docker-entrypoint-initdb.d:ro
    environment:
      POSTGRES_PASSWORD: pg-password-never-use-this-value

  graphql-engine:
    image: hasura/graphql-engine:v2.2.0
    environment:
      HASURA_GRAPHQL_DATABASE_URL: 'postgres://postgres:pg-password-never-use-this-value@localhost:5432/postgres'
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"HS256", "key":"5152fa850c02dc222631cca898ed1485821a70912a6e3649c49076912daa3b62182ba013315915d64f40cddfbb8b58eb5bd11ba225336a6af45bbae07ca873f3","issuer":"hasura-auth"}'
      HASURA_GRAPHQL_ADMIN_SECRET: hello123
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: public
      HASURA_GRAPHQL_LOG_LEVEL: debug
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'
      HASURA_GRAPHQL_SERVER_PORT: 8081
    deploy:
      resources:
        limits:
          memory: 250M

  auth:
    image: nhost/hasura-auth:latest
#    volumes:
#      - ./emails:/app/email-templates
    environment:
      AUTH_HOST: '0.0.0.0'
      HASURA_GRAPHQL_DATABASE_URL: 'postgres://postgres:pg-password-never-use-this-value@localhost:5432/postgres'
      HASURA_GRAPHQL_GRAPHQL_URL: http://localhost:8081/v1/graphql
      HASURA_GRAPHQL_JWT_SECRET: '{"type":"HS256", "key":"5152fa850c02dc222631cca898ed1485821a70912a6e3649c49076912daa3b62182ba013315915d64f40cddfbb8b58eb5bd11ba225336a6af45bbae07ca873f3","issuer":"hasura-auth"}'
      HASURA_GRAPHQL_ADMIN_SECRET: hello123
      AUTH_CLIENT_URL: http://localhost:3000
      AUTH_SMTP_HOST: mailhog
      AUTH_SMTP_PORT: 1025
      AUTH_SMTP_USER: user
      AUTH_SMTP_PASS: password
      AUTH_SMTP_SENDER: mail@example.com
  
  storage:
    image: nhost/hasura-storage:0.2.1
    environment:
      PUBLIC_URL: http://localhost:1337
      HASURA_METADATA: 1
      HASURA_ENDPOINT: http://localhost:8081/v1
      HASURA_GRAPHQL_ADMIN_SECRET: hello123
      S3_ACCESS_KEY: storage-access-key-never-use-this-value
      S3_SECRET_KEY: storage-secret-key-never-use-this-value
      S3_ENDPOINT: http://localhost:8484
      S3_BUCKET: nhost
      POSTGRES_MIGRATIONS: 1
      POSTGRES_MIGRATIONS_SOURCE: 'postgres@localhost:5432/postgres?sslmode=disable'
    command: serve

  functions:
    image: nhost/functions:latest
    volumes:
      - ./:/opt/project
      - functions_node_modules:/opt/project/node_modules
      - /opt/project/data/
      - /opt/project/initdb.d/

  minio:
    image: 'minio/minio:latest'
    entrypoint: sh
    command: -c 'mkdir -p /data/nhost && /opt/bin/minio server --address :8484 /data'
    environment:
      MINIO_ROOT_USER: storage-access-key-never-use-this-value
      MINIO_ROOT_PASSWORD: storage-secret-key-never-use-this-value
#    volumes:
#      - ./data/minio:/data

  mailhog:
    image: mailhog/mailhog
    environment:
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
      SMTP_PASS: password
      SMTP_USER: user
      SMTP_SECURE: 'false'
      SMTP_SENDER: hbp@hbp.com
#    volumes:
#      - ./data/mailhog:/maildir

volumes:
  functions_node_modules:
